export const USERS_FETCH_PENDING = 'USERS_FETCH_PENDING';
export const USERS_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
export const USERS_FETCH_REQUESTED = 'USERS_FETCH_REQUESTED';
export const USERS_FETCH_FAILED = 'USER_FETCH_FAILED';
export const USERS_FETCH_LOADING = 'USERS_FETCH_LOADING';
